-- 001_extensions_and_enums.sql
-- Simorgh Grid — core extensions and enumerated types.

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pgcrypto;
-- TimescaleDB: safe no-op if the image/extension isn't available (falls back to plain Postgres tables).
DO $$
BEGIN
  BEGIN
    CREATE EXTENSION IF NOT EXISTS timescaledb;
  EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'timescaledb extension not available, continuing with plain PostgreSQL tables';
  END;
END $$;

CREATE TYPE user_role AS ENUM (
  'ADMIN', 'EXECUTIVE', 'PROJECT_MANAGER', 'TECHNICAL_MANAGER',
  'PROTECTION_ENGINEER', 'FIELD_SERVICE_ENGINEER', 'VIEWER'
);

CREATE TYPE project_status AS ENUM (
  'PLANNING', 'ENGINEERING', 'PROCUREMENT', 'MANUFACTURING', 'FAT',
  'INSTALLATION', 'COMMISSIONING', 'RUNNING', 'COMPLETED', 'BLOCKED'
);

CREATE TYPE project_type AS ENUM (
  'MV_SWITCHGEAR', 'HV_SWITCHGEAR', 'SUBSTATION_TURNKEY', 'RELAY_UPGRADE',
  'SCADA_INTEGRATION', 'PANEL_MANUFACTURING', 'OTHER'
);

CREATE TYPE comm_status AS ENUM ('ONLINE', 'OFFLINE', 'DEGRADED', 'UNKNOWN');
CREATE TYPE relay_health_status AS ENUM ('HEALTHY', 'WARNING', 'ATTENTION', 'CRITICAL', 'OFFLINE');
CREATE TYPE breaker_status AS ENUM ('OPEN', 'CLOSED', 'TRIPPED', 'UNKNOWN');

CREATE TYPE event_severity AS ENUM ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO');

CREATE TYPE protection_function_code AS ENUM (
  'OVERCURRENT', 'EARTH_FAULT', 'SHORT_CIRCUIT', 'OVERVOLTAGE', 'UNDERVOLTAGE',
  'OVERFREQUENCY', 'UNDERFREQUENCY', 'TRANSFORMER_DIFFERENTIAL', 'BUSBAR_DIFFERENTIAL',
  'BREAKER_FAILURE', 'NEGATIVE_SEQUENCE', 'THERMAL_OVERLOAD', 'MOTOR_PROTECTION',
  'DISTANCE_PROTECTION', 'DIRECTIONAL_OVERCURRENT', 'LOSS_OF_VOLTAGE', 'LOSS_OF_CURRENT',
  'TRIP_CIRCUIT_FAILURE'
);

CREATE TYPE source_protocol AS ENUM (
  'IEC61850_MMS', 'IEC61850_GOOSE', 'IEC60870_5_104', 'DNP3', 'MODBUS_TCP', 'OPC_UA', 'REST', 'MQTT', 'SYNTHETIC'
);

CREATE TYPE fault_trip_status AS ENUM ('TRIPPED', 'NO_TRIP', 'ALARM_ONLY');
CREATE TYPE ack_status AS ENUM ('UNACKNOWLEDGED', 'ACKNOWLEDGED', 'AUTO_ACKNOWLEDGED');
CREATE TYPE root_cause_status AS ENUM ('PENDING', 'AI_SUGGESTED', 'ENGINEER_CONFIRMED', 'INCONCLUSIVE');
CREATE TYPE fault_resolution_status AS ENUM ('OPEN', 'INVESTIGATING', 'RESOLVED', 'CLOSED_NO_ACTION');

CREATE TYPE alarm_priority AS ENUM ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO');
CREATE TYPE alarm_status AS ENUM ('OPEN', 'ACKNOWLEDGED', 'ESCALATED', 'SUPPRESSED', 'CLOSED');

CREATE TYPE work_order_status AS ENUM (
  'OPEN', 'ANALYSIS', 'ASSIGNED', 'FIELD_INSPECTION', 'REPAIR', 'TEST', 'VERIFIED', 'CLOSED'
);
CREATE TYPE work_order_priority AS ENUM ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW');

CREATE TYPE notification_channel AS ENUM ('DASHBOARD', 'EMAIL', 'SMS', 'PUSH');
CREATE TYPE notification_status AS ENUM ('PENDING', 'SENT', 'FAILED', 'READ');
