-- 017_full_location_hierarchy.sql
-- Adds the remaining Iranian provinces and their counties (shahrestan), and makes the
-- location tables extensible so a site anywhere in the world can be registered.
--
-- WHY: the demo seed carried 13 provinces and 24 cities, so most real Electro Kavir sites
-- had nowhere to be filed. Iranian counties are seeded here; every other country is served
-- by user-created regions and cities (see is_user_created), because pre-loading a world
-- gazetteer would be far more data than this application needs and would still be missing
-- exactly the town a panel happens to ship to.

ALTER TABLE provinces ADD COLUMN IF NOT EXISTS is_user_created boolean NOT NULL DEFAULT false;
ALTER TABLE cities    ADD COLUMN IF NOT EXISTS is_user_created boolean NOT NULL DEFAULT false;

-- Stops the same town being added twice under one province with different capitalisation.
CREATE UNIQUE INDEX IF NOT EXISTS cities_province_name_uniq ON cities (province_id, lower(name_en));
CREATE UNIQUE INDEX IF NOT EXISTS provinces_country_name_uniq ON provinces (coalesce(country_code,'??'), lower(name_en));

INSERT INTO provinces (id, name_en, name_fa, country_code) VALUES
  ('IR-ALB', 'Alborz', 'البرز', 'IR'),
  ('IR-ARD', 'Ardabil', 'اردبیل', 'IR'),
  ('IR-BSH', 'Bushehr', 'بوشهر', 'IR'),
  ('IR-CHB', 'Chaharmahal and Bakhtiari', 'چهارمحال و بختیاری', 'IR'),
  ('IR-EAZ', 'East Azerbaijan', 'آذربایجان شرقی', 'IR'),
  ('IR-ESF', 'Isfahan', 'اصفهان', 'IR'),
  ('IR-FAR', 'Fars', 'فارس', 'IR'),
  ('IR-GIL', 'Gilan', 'گیلان', 'IR'),
  ('IR-GLS', 'Golestan', 'گلستان', 'IR'),
  ('IR-HMD', 'Hamadan', 'همدان', 'IR'),
  ('IR-HOR', 'Hormozgan', 'هرمزگان', 'IR'),
  ('IR-ILM', 'Ilam', 'ایلام', 'IR'),
  ('IR-KBA', 'Kohgiluyeh and Boyer-Ahmad', 'کهگیلویه و بویراحمد', 'IR'),
  ('IR-KER', 'Kerman', 'کرمان', 'IR'),
  ('IR-KHZ', 'Khuzestan', 'خوزستان', 'IR'),
  ('IR-KRD', 'Kurdistan', 'کردستان', 'IR'),
  ('IR-KRZ', 'Khorasan Razavi', 'خراسان رضوی', 'IR'),
  ('IR-KSH', 'Kermanshah', 'کرمانشاه', 'IR'),
  ('IR-LRS', 'Lorestan', 'لرستان', 'IR'),
  ('IR-MKZ', 'Markazi', 'مرکزی', 'IR'),
  ('IR-MZN', 'Mazandaran', 'مازندران', 'IR'),
  ('IR-NKH', 'North Khorasan', 'خراسان شمالی', 'IR'),
  ('IR-QOM', 'Qom', 'قم', 'IR'),
  ('IR-QZV', 'Qazvin', 'قزوین', 'IR'),
  ('IR-SBL', 'Sistan and Baluchestan', 'سیستان و بلوچستان', 'IR'),
  ('IR-SEM', 'Semnan', 'سمنان', 'IR'),
  ('IR-SKH', 'South Khorasan', 'خراسان جنوبی', 'IR'),
  ('IR-THR', 'Tehran', 'تهران', 'IR'),
  ('IR-WAZ', 'West Azerbaijan', 'آذربایجان غربی', 'IR'),
  ('IR-YAZ', 'Yazd', 'یزد', 'IR'),
  ('IR-ZAN', 'Zanjan', 'زنجان', 'IR')
ON CONFLICT (id) DO NOTHING;

INSERT INTO cities (id, province_id, name_en, name_fa) VALUES
  ('city_karaj', 'IR-ALB', 'Karaj', 'کرج'),
  ('city_savojbolagh', 'IR-ALB', 'Savojbolagh', 'ساوجبلاغ'),
  ('city_nazarabad', 'IR-ALB', 'Nazarabad', 'نظرآباد'),
  ('city_taleqan', 'IR-ALB', 'Taleqan', 'طالقان'),
  ('city_eshtehard', 'IR-ALB', 'Eshtehard', 'اشتهارد'),
  ('city_fardis', 'IR-ALB', 'Fardis', 'فردیس'),
  ('city_asara', 'IR-ALB', 'Asara', 'اسارا'),
  ('city_ardabil', 'IR-ARD', 'Ardabil', 'اردبیل'),
  ('city_parsabad', 'IR-ARD', 'Parsabad', 'پارس‌آباد'),
  ('city_meshgin_shahr', 'IR-ARD', 'Meshgin Shahr', 'مشگین‌شهر'),
  ('city_khalkhal', 'IR-ARD', 'Khalkhal', 'خلخال'),
  ('city_germi', 'IR-ARD', 'Germi', 'گرمی'),
  ('city_bileh_savar', 'IR-ARD', 'Bileh Savar', 'بیله‌سوار'),
  ('city_namin', 'IR-ARD', 'Namin', 'نمین'),
  ('city_nir', 'IR-ARD', 'Nir', 'نیر'),
  ('city_kowsar', 'IR-ARD', 'Kowsar', 'کوثر'),
  ('city_sareyn', 'IR-ARD', 'Sareyn', 'سرعین'),
  ('city_aslan_duz', 'IR-ARD', 'Aslan Duz', 'اصلان‌دوز'),
  ('city_bushehr', 'IR-BSH', 'Bushehr', 'بوشهر'),
  ('city_dashtestan', 'IR-BSH', 'Dashtestan', 'دشتستان'),
  ('city_kangan', 'IR-BSH', 'Kangan', 'کنگان'),
  ('city_genaveh', 'IR-BSH', 'Genaveh', 'گناوه'),
  ('city_dayyer', 'IR-BSH', 'Dayyer', 'دیر'),
  ('city_deylam', 'IR-BSH', 'Deylam', 'دیلم'),
  ('city_dashti', 'IR-BSH', 'Dashti', 'دشتی'),
  ('city_jam', 'IR-BSH', 'Jam', 'جم'),
  ('city_asaluyeh', 'IR-BSH', 'Asaluyeh', 'عسلویه'),
  ('city_tangestan', 'IR-BSH', 'Tangestan', 'تنگستان'),
  ('city_shahrekord', 'IR-CHB', 'Shahrekord', 'شهرکرد'),
  ('city_borujen', 'IR-CHB', 'Borujen', 'بروجن'),
  ('city_lordegan', 'IR-CHB', 'Lordegan', 'لردگان'),
  ('city_farsan', 'IR-CHB', 'Farsan', 'فارسان'),
  ('city_ardal', 'IR-CHB', 'Ardal', 'اردل'),
  ('city_kuhrang', 'IR-CHB', 'Kuhrang', 'کوهرنگ'),
  ('city_kiar', 'IR-CHB', 'Kiar', 'کیار'),
  ('city_saman', 'IR-CHB', 'Saman', 'سامان'),
  ('city_ben', 'IR-CHB', 'Ben', 'بن'),
  ('city_khanmirza', 'IR-CHB', 'Khanmirza', 'خانمیرزا'),
  ('city_tabriz', 'IR-EAZ', 'Tabriz', 'تبریز'),
  ('city_maragheh', 'IR-EAZ', 'Maragheh', 'مراغه'),
  ('city_marand', 'IR-EAZ', 'Marand', 'مرند'),
  ('city_mianeh', 'IR-EAZ', 'Mianeh', 'میانه'),
  ('city_ahar', 'IR-EAZ', 'Ahar', 'اهر'),
  ('city_bonab', 'IR-EAZ', 'Bonab', 'بناب'),
  ('city_sarab', 'IR-EAZ', 'Sarab', 'سراب'),
  ('city_shabestar', 'IR-EAZ', 'Shabestar', 'شبستر'),
  ('city_azarshahr', 'IR-EAZ', 'Azarshahr', 'آذرشهر'),
  ('city_bostanabad', 'IR-EAZ', 'Bostanabad', 'بستان‌آباد'),
  ('city_jolfa', 'IR-EAZ', 'Jolfa', 'جلفا'),
  ('city_kaleybar', 'IR-EAZ', 'Kaleybar', 'کلیبر'),
  ('city_malekan', 'IR-EAZ', 'Malekan', 'ملکان'),
  ('city_osku', 'IR-EAZ', 'Osku', 'اسکو'),
  ('city_heris', 'IR-EAZ', 'Heris', 'هریس'),
  ('city_charuymaq', 'IR-EAZ', 'Charuymaq', 'چاراویماق'),
  ('city_hashtrud', 'IR-EAZ', 'Hashtrud', 'هشترود'),
  ('city_varzaqan', 'IR-EAZ', 'Varzaqan', 'ورزقان'),
  ('city_ajabshir', 'IR-EAZ', 'Ajabshir', 'عجب‌شیر'),
  ('city_khoda_afarin', 'IR-EAZ', 'Khoda Afarin', 'خداآفرین'),
  ('city_isfahan', 'IR-ESF', 'Isfahan', 'اصفهان'),
  ('city_kashan', 'IR-ESF', 'Kashan', 'کاشان'),
  ('city_khomeyni_shahr', 'IR-ESF', 'Khomeyni Shahr', 'خمینی‌شهر'),
  ('city_najafabad', 'IR-ESF', 'Najafabad', 'نجف‌آباد'),
  ('city_shahin_shahr_va_meymeh', 'IR-ESF', 'Shahin Shahr va Meymeh', 'شاهین‌شهر و میمه'),
  ('city_falavarjan', 'IR-ESF', 'Falavarjan', 'فلاورجان'),
  ('city_lenjan', 'IR-ESF', 'Lenjan', 'لنجان'),
  ('city_mobarakeh', 'IR-ESF', 'Mobarakeh', 'مبارکه'),
  ('city_shahreza', 'IR-ESF', 'Shahreza', 'شهرضا'),
  ('city_golpayegan', 'IR-ESF', 'Golpayegan', 'گلپایگان'),
  ('city_khansar', 'IR-ESF', 'Khansar', 'خوانسار'),
  ('city_natanz', 'IR-ESF', 'Natanz', 'نطنز'),
  ('city_ardestan', 'IR-ESF', 'Ardestan', 'اردستان'),
  ('city_naein', 'IR-ESF', 'Naein', 'نایین'),
  ('city_aran_va_bidgol', 'IR-ESF', 'Aran va Bidgol', 'آران و بیدگل'),
  ('city_borkhar', 'IR-ESF', 'Borkhar', 'برخوار'),
  ('city_tiran_va_karvan', 'IR-ESF', 'Tiran va Karvan', 'تیران و کرون'),
  ('city_semirom', 'IR-ESF', 'Semirom', 'سمیرم'),
  ('city_dehaqan', 'IR-ESF', 'Dehaqan', 'دهاقان'),
  ('city_fereydan', 'IR-ESF', 'Fereydan', 'فریدن'),
  ('city_fereydunshahr', 'IR-ESF', 'Fereydunshahr', 'فریدون‌شهر'),
  ('city_chadegan', 'IR-ESF', 'Chadegan', 'چادگان'),
  ('city_buin_va_miandasht', 'IR-ESF', 'Buin va Miandasht', 'بویین و میاندشت'),
  ('city_khur_va_biabanak', 'IR-ESF', 'Khur va Biabanak', 'خور و بیابانک'),
  ('city_shiraz', 'IR-FAR', 'Shiraz', 'شیراز'),
  ('city_marvdasht', 'IR-FAR', 'Marvdasht', 'مرودشت'),
  ('city_kazerun', 'IR-FAR', 'Kazerun', 'کازرون'),
  ('city_jahrom', 'IR-FAR', 'Jahrom', 'جهرم'),
  ('city_fasa', 'IR-FAR', 'Fasa', 'فسا'),
  ('city_darab', 'IR-FAR', 'Darab', 'داراب'),
  ('city_larestan', 'IR-FAR', 'Larestan', 'لارستان'),
  ('city_firuzabad', 'IR-FAR', 'Firuzabad', 'فیروزآباد'),
  ('city_mamasani', 'IR-FAR', 'Mamasani', 'ممسنی'),
  ('city_abadeh', 'IR-FAR', 'Abadeh', 'آباده'),
  ('city_eqlid', 'IR-FAR', 'Eqlid', 'اقلید'),
  ('city_estahban', 'IR-FAR', 'Estahban', 'استهبان'),
  ('city_neyriz', 'IR-FAR', 'Neyriz', 'نی‌ریز'),
  ('city_sepidan', 'IR-FAR', 'Sepidan', 'سپیدان'),
  ('city_zarrin_dasht', 'IR-FAR', 'Zarrin Dasht', 'زرین‌دشت'),
  ('city_khonj', 'IR-FAR', 'Khonj', 'خنج'),
  ('city_gerash', 'IR-FAR', 'Gerash', 'گراش'),
  ('city_lamerd', 'IR-FAR', 'Lamerd', 'لامرد'),
  ('city_mohr', 'IR-FAR', 'Mohr', 'مهر'),
  ('city_farashband', 'IR-FAR', 'Farashband', 'فراشبند'),
  ('city_qir_va_karzin', 'IR-FAR', 'Qir va Karzin', 'قیر و کارزین'),
  ('city_kavar', 'IR-FAR', 'Kavar', 'کوار'),
  ('city_sarvestan', 'IR-FAR', 'Sarvestan', 'سروستان'),
  ('city_arsanjan', 'IR-FAR', 'Arsanjan', 'ارسنجان'),
  ('city_bavanat', 'IR-FAR', 'Bavanat', 'بوانات'),
  ('city_khorrambid', 'IR-FAR', 'Khorrambid', 'خرم‌بید'),
  ('city_pasargad', 'IR-FAR', 'Pasargad', 'پاسارگاد'),
  ('city_rostam', 'IR-FAR', 'Rostam', 'رستم'),
  ('city_kharameh', 'IR-FAR', 'Kharameh', 'خرامه'),
  ('city_zarqan', 'IR-FAR', 'Zarqan', 'زرقان'),
  ('city_beyza', 'IR-FAR', 'Beyza', 'بیضا'),
  ('city_rasht', 'IR-GIL', 'Rasht', 'رشت'),
  ('city_bandar_anzali', 'IR-GIL', 'Bandar Anzali', 'بندر انزلی'),
  ('city_lahijan', 'IR-GIL', 'Lahijan', 'لاهیجان'),
  ('city_langarud', 'IR-GIL', 'Langarud', 'لنگرود'),
  ('city_talesh', 'IR-GIL', 'Talesh', 'تالش'),
  ('city_astara', 'IR-GIL', 'Astara', 'آستارا'),
  ('city_astaneh_ye_ashrafiyeh', 'IR-GIL', 'Astaneh-ye Ashrafiyeh', 'آستانه اشرفیه'),
  ('city_fuman', 'IR-GIL', 'Fuman', 'فومن'),
  ('city_sowme_eh_sara', 'IR-GIL', 'Sowme''eh Sara', 'صومعه‌سرا'),
  ('city_rudsar', 'IR-GIL', 'Rudsar', 'رودسر'),
  ('city_rudbar', 'IR-GIL', 'Rudbar', 'رودبار'),
  ('city_shaft', 'IR-GIL', 'Shaft', 'شفت'),
  ('city_masal', 'IR-GIL', 'Masal', 'ماسال'),
  ('city_amlash', 'IR-GIL', 'Amlash', 'املش'),
  ('city_siahkal', 'IR-GIL', 'Siahkal', 'سیاهکل'),
  ('city_rezvanshahr', 'IR-GIL', 'Rezvanshahr', 'رضوانشهر'),
  ('city_gorgan', 'IR-GLS', 'Gorgan', 'گرگان'),
  ('city_gonbad_e_kavus', 'IR-GLS', 'Gonbad-e Kavus', 'گنبد کاووس'),
  ('city_aliabad_e_katul', 'IR-GLS', 'Aliabad-e Katul', 'علی‌آباد کتول'),
  ('city_bandar_e_torkaman', 'IR-GLS', 'Bandar-e Torkaman', 'بندر ترکمن'),
  ('city_kordkuy', 'IR-GLS', 'Kordkuy', 'کردکوی'),
  ('city_minudasht', 'IR-GLS', 'Minudasht', 'مینودشت'),
  ('city_azadshahr', 'IR-GLS', 'Azadshahr', 'آزادشهر'),
  ('city_ramian', 'IR-GLS', 'Ramian', 'رامیان'),
  ('city_aqqala', 'IR-GLS', 'Aqqala', 'آق‌قلا'),
  ('city_kalaleh', 'IR-GLS', 'Kalaleh', 'کلاله'),
  ('city_bandar_e_gaz', 'IR-GLS', 'Bandar-e Gaz', 'بندر گز'),
  ('city_galikash', 'IR-GLS', 'Galikash', 'گالیکش'),
  ('city_gomishan', 'IR-GLS', 'Gomishan', 'گمیشان'),
  ('city_maraveh_tappeh', 'IR-GLS', 'Maraveh Tappeh', 'مراوه‌تپه'),
  ('city_hamadan', 'IR-HMD', 'Hamadan', 'همدان'),
  ('city_malayer', 'IR-HMD', 'Malayer', 'ملایر'),
  ('city_nahavand', 'IR-HMD', 'Nahavand', 'نهاوند'),
  ('city_tuyserkan', 'IR-HMD', 'Tuyserkan', 'تویسرکان'),
  ('city_asadabad', 'IR-HMD', 'Asadabad', 'اسدآباد'),
  ('city_bahar', 'IR-HMD', 'Bahar', 'بهار'),
  ('city_kabudarahang', 'IR-HMD', 'Kabudarahang', 'کبودرآهنگ'),
  ('city_razan', 'IR-HMD', 'Razan', 'رزن'),
  ('city_famenin', 'IR-HMD', 'Famenin', 'فامنین'),
  ('city_bandar_abbas', 'IR-HOR', 'Bandar Abbas', 'بندرعباس'),
  ('city_bandar_lengeh', 'IR-HOR', 'Bandar Lengeh', 'بندر لنگه'),
  ('city_minab', 'IR-HOR', 'Minab', 'میناب'),
  ('city_qeshm', 'IR-HOR', 'Qeshm', 'قشم'),
  ('city_rudan', 'IR-HOR', 'Rudan', 'رودان'),
  ('city_hajiabad', 'IR-HOR', 'Hajiabad', 'حاجی‌آباد'),
  ('city_bastak', 'IR-HOR', 'Bastak', 'بستک'),
  ('city_jask', 'IR-HOR', 'Jask', 'جاسک'),
  ('city_parsian', 'IR-HOR', 'Parsian', 'پارسیان'),
  ('city_bandar_khamir', 'IR-HOR', 'Bandar Khamir', 'بندر خمیر'),
  ('city_sirik', 'IR-HOR', 'Sirik', 'سیریک'),
  ('city_abumusa', 'IR-HOR', 'Abumusa', 'ابوموسی'),
  ('city_bashagard', 'IR-HOR', 'Bashagard', 'بشاگرد'),
  ('city_ilam', 'IR-ILM', 'Ilam', 'ایلام'),
  ('city_dehloran', 'IR-ILM', 'Dehloran', 'دهلران'),
  ('city_abdanan', 'IR-ILM', 'Abdanan', 'آبدانان'),
  ('city_darreh_shahr', 'IR-ILM', 'Darreh Shahr', 'دره‌شهر'),
  ('city_ivan', 'IR-ILM', 'Ivan', 'ایوان'),
  ('city_mehran', 'IR-ILM', 'Mehran', 'مهران'),
  ('city_malekshahi', 'IR-ILM', 'Malekshahi', 'ملکشاهی'),
  ('city_chardavol', 'IR-ILM', 'Chardavol', 'چرداول'),
  ('city_badreh', 'IR-ILM', 'Badreh', 'بدره'),
  ('city_sirvan', 'IR-ILM', 'Sirvan', 'سیروان'),
  ('city_boyer_ahmad', 'IR-KBA', 'Boyer-Ahmad', 'بویراحمد'),
  ('city_gachsaran', 'IR-KBA', 'Gachsaran', 'گچساران'),
  ('city_kohgiluyeh', 'IR-KBA', 'Kohgiluyeh', 'کهگیلویه'),
  ('city_bahmai', 'IR-KBA', 'Bahmai', 'بهمئی'),
  ('city_dana', 'IR-KBA', 'Dana', 'دنا'),
  ('city_charam', 'IR-KBA', 'Charam', 'چرام'),
  ('city_basht', 'IR-KBA', 'Basht', 'باشت'),
  ('city_landeh', 'IR-KBA', 'Landeh', 'لنده'),
  ('city_kerman', 'IR-KER', 'Kerman', 'کرمان'),
  ('city_rafsanjan', 'IR-KER', 'Rafsanjan', 'رفسنجان'),
  ('city_sirjan', 'IR-KER', 'Sirjan', 'سیرجان'),
  ('city_bam', 'IR-KER', 'Bam', 'بم'),
  ('city_jiroft', 'IR-KER', 'Jiroft', 'جیرفت'),
  ('city_zarand', 'IR-KER', 'Zarand', 'زرند'),
  ('city_baft', 'IR-KER', 'Baft', 'بافت'),
  ('city_bardsir', 'IR-KER', 'Bardsir', 'بردسیر'),
  ('city_shahr_e_babak', 'IR-KER', 'Shahr-e Babak', 'شهر بابک'),
  ('city_kahnuj', 'IR-KER', 'Kahnuj', 'کهنوج'),
  ('city_anar', 'IR-KER', 'Anar', 'انار'),
  ('city_rabor', 'IR-KER', 'Rabor', 'رابر'),
  ('city_rudbar_e_jonubi', 'IR-KER', 'Rudbar-e Jonubi', 'رودبار جنوب'),
  ('city_manujan', 'IR-KER', 'Manujan', 'منوجان'),
  ('city_qaleh_ganj', 'IR-KER', 'Qaleh Ganj', 'قلعه گنج'),
  ('city_faryab', 'IR-KER', 'Faryab', 'فاریاب'),
  ('city_narmashir', 'IR-KER', 'Narmashir', 'نرماشیر'),
  ('city_rigan', 'IR-KER', 'Rigan', 'ریگان'),
  ('city_fahraj', 'IR-KER', 'Fahraj', 'فهرج'),
  ('city_anbarabad', 'IR-KER', 'Anbarabad', 'عنبرآباد'),
  ('city_kuhbanan', 'IR-KER', 'Kuhbanan', 'کوهبنان'),
  ('city_ravar', 'IR-KER', 'Ravar', 'راور'),
  ('city_arzuiyeh', 'IR-KER', 'Arzuiyeh', 'ارزوئیه'),
  ('city_ahvaz', 'IR-KHZ', 'Ahvaz', 'اهواز'),
  ('city_abadan', 'IR-KHZ', 'Abadan', 'آبادان'),
  ('city_khorramshahr', 'IR-KHZ', 'Khorramshahr', 'خرمشهر'),
  ('city_dezful', 'IR-KHZ', 'Dezful', 'دزفول'),
  ('city_andimeshk', 'IR-KHZ', 'Andimeshk', 'اندیمشک'),
  ('city_shushtar', 'IR-KHZ', 'Shushtar', 'شوشتر'),
  ('city_masjed_soleyman', 'IR-KHZ', 'Masjed Soleyman', 'مسجد سلیمان'),
  ('city_behbahan', 'IR-KHZ', 'Behbahan', 'بهبهان'),
  ('city_izeh', 'IR-KHZ', 'Izeh', 'ایذه'),
  ('city_ramhormoz', 'IR-KHZ', 'Ramhormoz', 'رامهرمز'),
  ('city_shush', 'IR-KHZ', 'Shush', 'شوش'),
  ('city_bandar_mahshahr', 'IR-KHZ', 'Bandar Mahshahr', 'بندر ماهشهر'),
  ('city_omidiyeh', 'IR-KHZ', 'Omidiyeh', 'امیدیه'),
  ('city_baghmalek', 'IR-KHZ', 'Baghmalek', 'باغ‌ملک'),
  ('city_hendijan', 'IR-KHZ', 'Hendijan', 'هندیجان'),
  ('city_shadegan', 'IR-KHZ', 'Shadegan', 'شادگان'),
  ('city_dasht_e_azadegan', 'IR-KHZ', 'Dasht-e Azadegan', 'دشت آزادگان'),
  ('city_hoveyzeh', 'IR-KHZ', 'Hoveyzeh', 'هویزه'),
  ('city_lali', 'IR-KHZ', 'Lali', 'لالی'),
  ('city_gotvand', 'IR-KHZ', 'Gotvand', 'گتوند'),
  ('city_haftkel', 'IR-KHZ', 'Haftkel', 'هفتکل'),
  ('city_aghajari', 'IR-KHZ', 'Aghajari', 'آغاجاری'),
  ('city_ramshir', 'IR-KHZ', 'Ramshir', 'رامشیر'),
  ('city_karun', 'IR-KHZ', 'Karun', 'کارون'),
  ('city_bavi', 'IR-KHZ', 'Bavi', 'باوی'),
  ('city_hamidiyeh', 'IR-KHZ', 'Hamidiyeh', 'حمیدیه'),
  ('city_sanandaj', 'IR-KRD', 'Sanandaj', 'سنندج'),
  ('city_saqqez', 'IR-KRD', 'Saqqez', 'سقز'),
  ('city_marivan', 'IR-KRD', 'Marivan', 'مریوان'),
  ('city_bijar', 'IR-KRD', 'Bijar', 'بیجار'),
  ('city_qorveh', 'IR-KRD', 'Qorveh', 'قروه'),
  ('city_baneh', 'IR-KRD', 'Baneh', 'بانه'),
  ('city_kamyaran', 'IR-KRD', 'Kamyaran', 'کامیاران'),
  ('city_divandarreh', 'IR-KRD', 'Divandarreh', 'دیواندره'),
  ('city_dehgolan', 'IR-KRD', 'Dehgolan', 'دهگلان'),
  ('city_sarvabad', 'IR-KRD', 'Sarvabad', 'سروآباد'),
  ('city_mashhad', 'IR-KRZ', 'Mashhad', 'مشهد'),
  ('city_neyshabur', 'IR-KRZ', 'Neyshabur', 'نیشابور'),
  ('city_sabzevar', 'IR-KRZ', 'Sabzevar', 'سبزوار'),
  ('city_torbat_e_heydarieh', 'IR-KRZ', 'Torbat-e Heydarieh', 'تربت حیدریه'),
  ('city_torbat_e_jam', 'IR-KRZ', 'Torbat-e Jam', 'تربت جام'),
  ('city_quchan', 'IR-KRZ', 'Quchan', 'قوچان'),
  ('city_kashmar', 'IR-KRZ', 'Kashmar', 'کاشمر'),
  ('city_gonabad', 'IR-KRZ', 'Gonabad', 'گناباد'),
  ('city_chenaran', 'IR-KRZ', 'Chenaran', 'چناران'),
  ('city_fariman', 'IR-KRZ', 'Fariman', 'فریمان'),
  ('city_sarakhs', 'IR-KRZ', 'Sarakhs', 'سرخس'),
  ('city_taybad', 'IR-KRZ', 'Taybad', 'تایباد'),
  ('city_khaf', 'IR-KRZ', 'Khaf', 'خواف'),
  ('city_dargaz', 'IR-KRZ', 'Dargaz', 'درگز'),
  ('city_bardaskan', 'IR-KRZ', 'Bardaskan', 'بردسکن'),
  ('city_kalat', 'IR-KRZ', 'Kalat', 'کلات'),
  ('city_khoshab', 'IR-KRZ', 'Khoshab', 'خوشاب'),
  ('city_mahvelat', 'IR-KRZ', 'Mahvelat', 'مه‌ولات'),
  ('city_rashtkhar', 'IR-KRZ', 'Rashtkhar', 'رشتخوار'),
  ('city_zaveh', 'IR-KRZ', 'Zaveh', 'زاوه'),
  ('city_bajestan', 'IR-KRZ', 'Bajestan', 'بجستان'),
  ('city_binalud', 'IR-KRZ', 'Binalud', 'بینالود'),
  ('city_firuzeh', 'IR-KRZ', 'Firuzeh', 'فیروزه'),
  ('city_joveyn', 'IR-KRZ', 'Joveyn', 'جوین'),
  ('city_davarzan', 'IR-KRZ', 'Davarzan', 'داورزن'),
  ('city_kermanshah', 'IR-KSH', 'Kermanshah', 'کرمانشاه'),
  ('city_eslamabad_e_gharb', 'IR-KSH', 'Eslamabad-e Gharb', 'اسلام‌آباد غرب'),
  ('city_sonqor', 'IR-KSH', 'Sonqor', 'سنقر'),
  ('city_harsin', 'IR-KSH', 'Harsin', 'هرسین'),
  ('city_kangavar', 'IR-KSH', 'Kangavar', 'کنگاور'),
  ('city_sarpol_e_zahab', 'IR-KSH', 'Sarpol-e Zahab', 'سرپل ذهاب'),
  ('city_javanrud', 'IR-KSH', 'Javanrud', 'جوانرود'),
  ('city_paveh', 'IR-KSH', 'Paveh', 'پاوه'),
  ('city_gilan_e_gharb', 'IR-KSH', 'Gilan-e Gharb', 'گیلانغرب'),
  ('city_qasr_e_shirin', 'IR-KSH', 'Qasr-e Shirin', 'قصر شیرین'),
  ('city_salas_e_babajani', 'IR-KSH', 'Salas-e Babajani', 'ثلاث باباجانی'),
  ('city_sahneh', 'IR-KSH', 'Sahneh', 'صحنه'),
  ('city_dalahu', 'IR-KSH', 'Dalahu', 'دالاهو'),
  ('city_ravansar', 'IR-KSH', 'Ravansar', 'روانسر'),
  ('city_khorramabad', 'IR-LRS', 'Khorramabad', 'خرم‌آباد'),
  ('city_borujerd', 'IR-LRS', 'Borujerd', 'بروجرد'),
  ('city_dorud', 'IR-LRS', 'Dorud', 'دورود'),
  ('city_aligudarz', 'IR-LRS', 'Aligudarz', 'الیگودرز'),
  ('city_kuhdasht', 'IR-LRS', 'Kuhdasht', 'کوهدشت'),
  ('city_azna', 'IR-LRS', 'Azna', 'ازنا'),
  ('city_delfan', 'IR-LRS', 'Delfan', 'دلفان'),
  ('city_poldokhtar', 'IR-LRS', 'Poldokhtar', 'پلدختر'),
  ('city_selseleh', 'IR-LRS', 'Selseleh', 'سلسله'),
  ('city_rumeshkhan', 'IR-LRS', 'Rumeshkhan', 'رومشکان'),
  ('city_chegeni', 'IR-LRS', 'Chegeni', 'چگنی'),
  ('city_arak', 'IR-MKZ', 'Arak', 'اراک'),
  ('city_saveh', 'IR-MKZ', 'Saveh', 'ساوه'),
  ('city_khomein', 'IR-MKZ', 'Khomein', 'خمین'),
  ('city_mahallat', 'IR-MKZ', 'Mahallat', 'محلات'),
  ('city_delijan', 'IR-MKZ', 'Delijan', 'دلیجان'),
  ('city_shazand', 'IR-MKZ', 'Shazand', 'شازند'),
  ('city_tafresh', 'IR-MKZ', 'Tafresh', 'تفرش'),
  ('city_ashtian', 'IR-MKZ', 'Ashtian', 'آشتیان'),
  ('city_komijan', 'IR-MKZ', 'Komijan', 'کمیجان'),
  ('city_zarandieh', 'IR-MKZ', 'Zarandieh', 'زرندیه'),
  ('city_farahan', 'IR-MKZ', 'Farahan', 'فراهان'),
  ('city_khondab', 'IR-MKZ', 'Khondab', 'خنداب'),
  ('city_sari', 'IR-MZN', 'Sari', 'ساری'),
  ('city_babol', 'IR-MZN', 'Babol', 'بابل'),
  ('city_amol', 'IR-MZN', 'Amol', 'آمل'),
  ('city_qaem_shahr', 'IR-MZN', 'Qaem Shahr', 'قائم‌شهر'),
  ('city_behshahr', 'IR-MZN', 'Behshahr', 'بهشهر'),
  ('city_tonekabon', 'IR-MZN', 'Tonekabon', 'تنکابن'),
  ('city_chalus', 'IR-MZN', 'Chalus', 'چالوس'),
  ('city_nowshahr', 'IR-MZN', 'Nowshahr', 'نوشهر'),
  ('city_neka', 'IR-MZN', 'Neka', 'نکا'),
  ('city_babolsar', 'IR-MZN', 'Babolsar', 'بابلسر'),
  ('city_fereydunkenar', 'IR-MZN', 'Fereydunkenar', 'فریدونکنار'),
  ('city_juybar', 'IR-MZN', 'Juybar', 'جویبار'),
  ('city_mahmudabad', 'IR-MZN', 'Mahmudabad', 'محمودآباد'),
  ('city_nur', 'IR-MZN', 'Nur', 'نور'),
  ('city_ramsar', 'IR-MZN', 'Ramsar', 'رامسر'),
  ('city_galugah', 'IR-MZN', 'Galugah', 'گلوگاه'),
  ('city_miandorud', 'IR-MZN', 'Miandorud', 'میاندرود'),
  ('city_simorgh', 'IR-MZN', 'Simorgh', 'سیمرغ'),
  ('city_abbasabad', 'IR-MZN', 'Abbasabad', 'عباس‌آباد'),
  ('city_kelardasht', 'IR-MZN', 'Kelardasht', 'کلاردشت'),
  ('city_savadkuh', 'IR-MZN', 'Savadkuh', 'سوادکوه'),
  ('city_bojnord', 'IR-NKH', 'Bojnord', 'بجنورد'),
  ('city_shirvan', 'IR-NKH', 'Shirvan', 'شیروان'),
  ('city_esfarayen', 'IR-NKH', 'Esfarayen', 'اسفراین'),
  ('city_jajarm', 'IR-NKH', 'Jajarm', 'جاجرم'),
  ('city_maneh_va_samalqan', 'IR-NKH', 'Maneh va Samalqan', 'مانه و سملقان'),
  ('city_faruj', 'IR-NKH', 'Faruj', 'فاروج'),
  ('city_garmeh', 'IR-NKH', 'Garmeh', 'گرمه'),
  ('city_raz_va_jargalan', 'IR-NKH', 'Raz va Jargalan', 'راز و جرگلان'),
  ('city_qom', 'IR-QOM', 'Qom', 'قم'),
  ('city_kahak', 'IR-QOM', 'Kahak', 'کهک'),
  ('city_jafarabad', 'IR-QOM', 'Jafarabad', 'جعفرآباد'),
  ('city_salafchegan', 'IR-QOM', 'Salafchegan', 'سلفچگان'),
  ('city_qazvin', 'IR-QZV', 'Qazvin', 'قزوین'),
  ('city_takestan', 'IR-QZV', 'Takestan', 'تاکستان'),
  ('city_buin_zahra', 'IR-QZV', 'Buin Zahra', 'بویین‌زهرا'),
  ('city_abyek', 'IR-QZV', 'Abyek', 'آبیک'),
  ('city_alborz', 'IR-QZV', 'Alborz', 'البرز'),
  ('city_avaj', 'IR-QZV', 'Avaj', 'آوج'),
  ('city_zahedan', 'IR-SBL', 'Zahedan', 'زاهدان'),
  ('city_zabol', 'IR-SBL', 'Zabol', 'زابل'),
  ('city_chabahar', 'IR-SBL', 'Chabahar', 'چابهار'),
  ('city_iranshahr', 'IR-SBL', 'Iranshahr', 'ایرانشهر'),
  ('city_khash', 'IR-SBL', 'Khash', 'خاش'),
  ('city_saravan', 'IR-SBL', 'Saravan', 'سراوان'),
  ('city_nikshahr', 'IR-SBL', 'Nikshahr', 'نیک‌شهر'),
  ('city_konarak', 'IR-SBL', 'Konarak', 'کنارک'),
  ('city_sarbaz', 'IR-SBL', 'Sarbaz', 'سرباز'),
  ('city_delgan', 'IR-SBL', 'Delgan', 'دلگان'),
  ('city_zehak', 'IR-SBL', 'Zehak', 'زهک'),
  ('city_hirmand', 'IR-SBL', 'Hirmand', 'هیرمند'),
  ('city_mirjaveh', 'IR-SBL', 'Mirjaveh', 'میرجاوه'),
  ('city_qasr_e_qand', 'IR-SBL', 'Qasr-e Qand', 'قصرقند'),
  ('city_fanuj', 'IR-SBL', 'Fanuj', 'فنوج'),
  ('city_sib_va_suran', 'IR-SBL', 'Sib va Suran', 'سیب و سوران'),
  ('city_nimruz', 'IR-SBL', 'Nimruz', 'نیمروز'),
  ('city_bampur', 'IR-SBL', 'Bampur', 'بمپور'),
  ('city_hamun', 'IR-SBL', 'Hamun', 'هامون'),
  ('city_semnan', 'IR-SEM', 'Semnan', 'سمنان'),
  ('city_shahrud', 'IR-SEM', 'Shahrud', 'شاهرود'),
  ('city_damghan', 'IR-SEM', 'Damghan', 'دامغان'),
  ('city_garmsar', 'IR-SEM', 'Garmsar', 'گرمسار'),
  ('city_mehdishahr', 'IR-SEM', 'Mehdishahr', 'مهدی‌شهر'),
  ('city_sorkheh', 'IR-SEM', 'Sorkheh', 'سرخه'),
  ('city_aradan', 'IR-SEM', 'Aradan', 'آرادان'),
  ('city_miami', 'IR-SEM', 'Miami', 'میامی'),
  ('city_birjand', 'IR-SKH', 'Birjand', 'بیرجند'),
  ('city_qaen', 'IR-SKH', 'Qaen', 'قائن'),
  ('city_ferdows', 'IR-SKH', 'Ferdows', 'فردوس'),
  ('city_tabas', 'IR-SKH', 'Tabas', 'طبس'),
  ('city_nehbandan', 'IR-SKH', 'Nehbandan', 'نهبندان'),
  ('city_sarbisheh', 'IR-SKH', 'Sarbisheh', 'سربیشه'),
  ('city_darmian', 'IR-SKH', 'Darmian', 'درمیان'),
  ('city_boshruyeh', 'IR-SKH', 'Boshruyeh', 'بشرویه'),
  ('city_khusf', 'IR-SKH', 'Khusf', 'خوسف'),
  ('city_zirkuh', 'IR-SKH', 'Zirkuh', 'زیرکوه'),
  ('city_sarayan', 'IR-SKH', 'Sarayan', 'سرایان'),
  ('city_tehran', 'IR-THR', 'Tehran', 'تهران'),
  ('city_rey', 'IR-THR', 'Rey', 'ری'),
  ('city_shemiranat', 'IR-THR', 'Shemiranat', 'شمیرانات'),
  ('city_eslamshahr', 'IR-THR', 'Eslamshahr', 'اسلامشهر'),
  ('city_baharestan', 'IR-THR', 'Baharestan', 'بهارستان'),
  ('city_robat_karim', 'IR-THR', 'Robat Karim', 'رباط کریم'),
  ('city_shahriar', 'IR-THR', 'Shahriar', 'شهریار'),
  ('city_qods', 'IR-THR', 'Qods', 'قدس'),
  ('city_malard', 'IR-THR', 'Malard', 'ملارد'),
  ('city_pakdasht', 'IR-THR', 'Pakdasht', 'پاکدشت'),
  ('city_varamin', 'IR-THR', 'Varamin', 'ورامین'),
  ('city_qarchak', 'IR-THR', 'Qarchak', 'قرچک'),
  ('city_pishva', 'IR-THR', 'Pishva', 'پیشوا'),
  ('city_damavand', 'IR-THR', 'Damavand', 'دماوند'),
  ('city_firuzkuh', 'IR-THR', 'Firuzkuh', 'فیروزکوه'),
  ('city_pardis', 'IR-THR', 'Pardis', 'پردیس'),
  ('city_urmia', 'IR-WAZ', 'Urmia', 'ارومیه'),
  ('city_khoy', 'IR-WAZ', 'Khoy', 'خوی'),
  ('city_miandoab', 'IR-WAZ', 'Miandoab', 'میاندوآب'),
  ('city_mahabad', 'IR-WAZ', 'Mahabad', 'مهاباد'),
  ('city_bukan', 'IR-WAZ', 'Bukan', 'بوکان'),
  ('city_naqadeh', 'IR-WAZ', 'Naqadeh', 'نقده'),
  ('city_salmas', 'IR-WAZ', 'Salmas', 'سلماس'),
  ('city_piranshahr', 'IR-WAZ', 'Piranshahr', 'پیرانشهر'),
  ('city_sardasht', 'IR-WAZ', 'Sardasht', 'سردشت'),
  ('city_oshnavieh', 'IR-WAZ', 'Oshnavieh', 'اشنویه'),
  ('city_takab', 'IR-WAZ', 'Takab', 'تکاب'),
  ('city_shahin_dezh', 'IR-WAZ', 'Shahin Dezh', 'شاهین‌دژ'),
  ('city_maku', 'IR-WAZ', 'Maku', 'ماکو'),
  ('city_chaldoran', 'IR-WAZ', 'Chaldoran', 'چالدران'),
  ('city_poldasht', 'IR-WAZ', 'Poldasht', 'پلدشت'),
  ('city_chaypareh', 'IR-WAZ', 'Chaypareh', 'چایپاره'),
  ('city_showt', 'IR-WAZ', 'Showt', 'شوط'),
  ('city_yazd', 'IR-YAZ', 'Yazd', 'یزد'),
  ('city_meybod', 'IR-YAZ', 'Meybod', 'میبد'),
  ('city_ardakan', 'IR-YAZ', 'Ardakan', 'اردکان'),
  ('city_bafq', 'IR-YAZ', 'Bafq', 'بافق'),
  ('city_mehriz', 'IR-YAZ', 'Mehriz', 'مهریز'),
  ('city_taft', 'IR-YAZ', 'Taft', 'تفت'),
  ('city_abarkuh', 'IR-YAZ', 'Abarkuh', 'ابرکوه'),
  ('city_khatam', 'IR-YAZ', 'Khatam', 'خاتم'),
  ('city_ashkezar', 'IR-YAZ', 'Ashkezar', 'اشکذر'),
  ('city_bahabad', 'IR-YAZ', 'Bahabad', 'بهاباد'),
  ('city_zarch', 'IR-YAZ', 'Zarch', 'زارچ'),
  ('city_zanjan', 'IR-ZAN', 'Zanjan', 'زنجان'),
  ('city_abhar', 'IR-ZAN', 'Abhar', 'ابهر'),
  ('city_khodabandeh', 'IR-ZAN', 'Khodabandeh', 'خدابنده'),
  ('city_khorramdarreh', 'IR-ZAN', 'Khorramdarreh', 'خرمدره'),
  ('city_tarom', 'IR-ZAN', 'Tarom', 'طارم'),
  ('city_mahneshan', 'IR-ZAN', 'Mahneshan', 'ماه‌نشان'),
  ('city_ijrud', 'IR-ZAN', 'Ijrud', 'ایجرود'),
  ('city_soltaniyeh', 'IR-ZAN', 'Soltaniyeh', 'سلطانیه')
ON CONFLICT DO NOTHING;

